---
title: "arya-class-5-math"
subtitle: "Arya Singh"
author: "Onkar Singh"
institute: "Shri Ram Global School"
date: "2021/11/20 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

class: inverse, center, middle
# Chapter 4: Factors and Multiples

---
class: inverse, center, middle
# Chapter 5: Fractions


- Pankaj takes 2/6 of an hour to reach school. In how many mintures does he reach school? 

Answer: 2*60/6 = 20 

- Bina and Mina ordered a Pizza? 

Bina ate 3/6 of the pizza
Mina ate 2/6 of the pizza                                                                                                                         


a. Who ate more pizza? 

b. What fraction of the pizza did they eat together? 

c. what fraction of the pizza is left. 


---

### Like and unlike fractions

- Fractions with the same denominator are called like fractions. 

- Fractions with different denominators are called unlike fractions. 

### Proper and Improper Fractions and Mixed Numbers
- A fraction in which the numerator is smaller than the denominator is a proper fraction. 

- A fraction in which the numerator is greater than the denominator is an improper fraction

- A mixed number is a combination of a whole number and a fraction. 
- The value of a proper fraction is less than 1
- The value of an improper fractio is greater than 1
- The value of a mixed fraction is greater than 1


---

### Fraction Continued
- Change into mixed numbers: 7/3, 19/2 and 11/4. 
- Change into improper fractions: 4 1/2, 3 1/3, 6 3/4

###Equivalent Fraction

- The equivalent fraction can be found by multiplying the numerator and denominator by the same number 
- The equivalent fraction can also be found by dividing the numerator and denominator by the same number

- By cross multiplication we can easily check if the two fraction are requivalent
 e.g. 1/3 and 4/12 
 1*12 = 3*4
12 = 12 i.e. equivalent franction. 

- fraction is in its lowest terms when the numerator and denominator have no common factor except 1. Divide the numerator and denominator by common factors until only 1 is left as the common factor. 

- One can also divide the numerator and denominator by their highest common factor (HCF). Then one can get the result in a single step. 

---

- The fraction with greater numerator is greater. 

- In unlike fraction with the same numerator, the fraction with the greater denominator is smaller. 



---
class: inverse, center, middle

# Chapter 7: Symmetry, Patterns and Nets

---
class: inverse, center, middle
# Chapter 8: Geometry


---
class: inverse, center, middle
Final Exam on 23rd March

9am to 1030am 

693 172 0881

Ms. Nidhi Agrawal
nidhi.a@srgsomr.org

New Maths Time

---
class: inverse, center, middle
Chapter 6: Decimal Numbers

---
class: inverse, center, middle
Chapter 8:  Geometry

---
class: inverse, center, middle
Chapter 9: Measurements

---
class: inverse, center, middle
Chapter 10: Perimeter, Area and Volume
---
class: inverse, center, middle
Chapter 13: Graphs




