---
title: "arya-class-5-english"
subtitle: "Arya Singh"
author: "Onkar Singh"
institute: "Shri Ram Global School"
date: "2021/11/20 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: inverse, center, middle
```{r , echo=FALSE}
library(xaringanthemer)

style_duo(
  primary_color = "#1F4257",
  secondary_color = "#F97B64",
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "300", "300i"),
  code_font_google   = google_font("Fira Mono")
)
```
# Gulmohar
# Chapter 4: Five Children and It

---



---
class: inverse, center, middle
# Gulmohar
# Poem: Roadside Locksmith

---
class: inverse, center, middle
# Enjoying Grammar
# Chapter 6: The Simple Present and The Present Continuous Tense

---
class: inverse, center, middle
# Enjoying Grammar
# Chapter 7: The Simple Past and The Past Continous Tenses

---
class: inverse, center, middle
# Creative Writing

---
class: inverse, center, middle
# Letter Writing

---
class: inverse, center, middle
# Reading Comprehension

---

# Word Synonyms

.pull-left[

- abrupt = sudden, hasty, unexpected

- adamant = studborn, inflexible

- adhere = comply, observe

- audacity = boldness, courage

- captivity = imprisonment, confinement

- decipher = interpret, reveal 

- deliberate = planned, intentional 

- despair = hopelessness, anguish

- disastrous = terrible, devastating




]

.pull-right[

- dwell = reside, inhabit, live

- eccentric = strange, abnormal

- eloquence = expression, fluency 

- enlighten = disclose, illuminate

- escalate = heighten, intensify

- feeble = weak, frail

- fragile = breakable, delicate

- grudge = hatred, aversion

- guile = cunning, deceit

- haughty = arrogance, pompous

- immaculate = clean, spotless

]

---
# Word Synonyms Contd

.pull-left[



- juvenile = young, tender

- nimble = prompt, active

- rectify = amend, remedy

- savage = wild, untamed

- startled = frightened, shocked





]

.pull-right[





]


---

## Term 2 Exam Preparation 
### Exam Date: 6 December 2021

### Chapter 4: Five Children and It
### Poem: The Roadside Locksmith
### Chapter 6: Simple Present and Present Continous Tense
### Chapter 7: The Simple Past and Past Continous Tense
### Letter writing and Reading Comprehension



---

### The Roadside Locksmith 

---
### Understanding the Peom

A.    1. The locksmith sits on the roadside with this wares
      A tilted black umbrella blocks the sun's glare
      
      a. What are the wares of the locksmith? 
      Ans: Locks and keys are the wares of the locksmith. 
      
      b. What time of the day is it when the locksmith is at work? How do you know? 
      Answe: It is midday as the locksmith is using an umbrella to block the sun's glare. 
      
      2. A mountain of master keys
        heaped on the ground
        
      a. Why is the word mountain used to describe the keys
      
      Ans: the keys form a large heaps which looks like a mountain and hence 
      mountain has been used to describe the keys. 
      
      b. Why does the locksmith have keys heaped on the groud? 
      Ans: The locksmith has keys heaped on the ground because it is a part of his job to sell locks and keys, to repair locks and keys and make new keys for locks that can't be opened. 

---
    3. The locksmith has the answer 
    to every locked door. 
      a. What does the locksmith do? 
      
      b. Why does he have an answer to every locked door? 
      
    4. Don't worry, don't fret
      Don't be sad, don't despair
      He'll find a friendly lock 
      to complete the pair
      
      a. Why does the speaker say there is no reason to fret or despair? 
      Answer: The speaker said so because the locksmith can help anyone with any
      type of keys or locks. 
      
      b. How can the locksmith helps us if ever we are in need of help? 
      
      Answer: 
      
      c. What is the 'pair' that the speaker is referring to ? 
      
      
      
    5. Which literary device is used in the poem? Give example. 
    
    Answer: The poet has used personification in the poem. 
    Example: And you have a key that i s lonely and lost
            he will find a *** friendly lock ***. 
---
### Words in Use
### Match the highlighted words with their correct synonyms from the choices given

1. wares

a. ornaments b. **goods** c. food

2. tilted

a. straightened b. moved c. **slanted**

3. blocks

a. **stops** b. hides c. allows

4. heaped

a. built b. covered **c. stacked**

5. Fret

a. **worry** b. happy c. doubtful 

---
### Chapter 4: Five Children and It

1. What were the children doing when they found the sand-fairy? 

Answer: The five children were building a sand castle in a big gravel pit, when they found the sand fairy. 

2. What was the name of hte sand-fairy? Describle it in a few setences? 

Answer: The name of the sand-fairy was psammead. It was about the size of the a large cast but with arms, legs and feet and hands like monkeys, long whiskers and pointed ears like a bat.
its eyes were on stalk like a snails horn an dit could stretch or shorten. 

3. Do you think the children were happy when their second wish came true? Explain. 

Answer: The children's second wish was to become beautiful but they were not happy when the wish came true. They felt that they looked strange and completely different. The looked like silly greeting cards, which meant, they looked too bright in an unusual way. 

---

## Q&A Contd...

4. Why did Martha not believe what the children told her? What did they do when Martha sent them away? 

Answer: Martha did not believe the children because they looked so different that she could not 
recognize them. When Martha sent them away, they began to wonder down the lane. Finally, they sat under a hedge and fell asleep there. 

5. Why did Martha let the children into the house again? 

Answer: After the sun had set, the children changed back to their normal selves. So when they came back home, Martha let them back into the house. 


### Reference to the Context

"Afraid!" repeated the creature indignantly. "Me? Don't you know a Psammead when you see one?" 

  - Who is the speaker
  The speaker of these lines is the sand-fairy Psammead. 
  
  - Who is the Psammead speaking for? 

---
# Appreciating the text

1. Tick the words that suit the Psammead the best. There can be more than one answer

  a. moody b. patient c. kind d. friendly e. lonely 6. pleasant
  
2. What kind of a story do you think Five Children and It is? Tick the word that describe the story best

a. comedy   b. ***fantasy***    c. tragedy


---

The Simple Present and the Present Continuous


---
The Simple Past and the Past Continuous Tenses



---
class: inverse, center, middle
Final Exam on 17th March

9am to 1030am 

390 148 2471

Ms. Neha

neha@srgsomr.org

Gulmohar

Enjoying Grammar

Creative Writing

---
class: inverse, center, middle
# Gulmohar
# Chapter 7: The Thief is Caught

---
class: inverse, center, middle
# Gulmohar
# Chapter 11:  The Piper of Manas
---
class: inverse, center, middle
# Gulmohar
# Poem Old Mister Laughter

---
class: inverse, center, middle
# Enjoying Grammar
# Chapter 15: Subject Verb Agreement

---
class: inverse, center, middle
# Enjoying Grammar
# Chapter 16: Phrases and Clauses

---
class: inverse, center, middle
# Enjoying Grammar
# Chapter 23: Active Passive Voice


---
class: inverse, center, middle
# Enjoying Grammar
# Chapter 24: Direct and Indirect Speech


---
class: inverse, center, middle
# Creative Writing
# Notice Writing


---
class: inverse, center, middle
# Creative Writing
# Comprehension
